df_cart/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [

    path('',views.cart),
    path('<int:gid>/<int:count>/',views.add),
    path('edit/<int:cart_id>/<int:count>/',views.edit),
    path('delete/<int:id>/',views.delete),
]

df_user/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import include
from .import views

urlpatterns = [
    path('register/', views.register),
    path('login/', views.login),
    path('login_handle/',views.login_handle),
    path('info/', views.info),
    path('order/<int:pindex>/', views.order),
    path('site/', views.site),
    path('register_handle/', views.register_handle),
    path('logout/',views.logout),
]

freshdaily/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('df_user.urls')),
    path('goods/',include('df_goods.urls')),
    path('tinymce/',include('tinymce.urls')),
    path('cart/',include('df_cart.urls')),
    path('order/',include('df_order.urls')),
    path('search/',include('haystack.urls')),

]

df_order/models.py
from django.db import models


# Create your models here.
class OrderInfo(models.Model):
    oid = models.CharField(max_length=20,primary_key=True)
    user = models.ForeignKey('df_user.UserInfo',on_delete=models.CASCADE)
    odate = models.DateTimeField(auto_now=True)
    oIsPay = models.BooleanField(default=False)
    ototal = models.DecimalField(max_digits=5,decimal_places=2)
    oaddress = models.CharField(max_length=150)


class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('df_goods.GoodsInfo',on_delete=models.CASCADE)
    order = models.ForeignKey(OrderInfo,on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=5,decimal_places=2)
    count = models.IntegerField()

df_user/models.py
from django.db import models

# Create your models here.
class UserInfo(models.Model):
    uname = models.CharField(max_length=20)
    upwd = models.CharField(max_length=40)
    uemail = models.CharField(max_length=30)
    ushou = models.CharField(max_length=20,default='')
    uaddress = models.CharField(max_length=100,default='')
    uyoubian = models.CharField(max_length=6,default='')
    uphone = models.CharField(max_length=11,default='')

df_user/views.py
from django.shortcuts import render, redirect, HttpResponse
from hashlib import sha1
from .models import *
from df_goods.models import *
from django.http import JsonResponse, HttpResponseRedirect
from . import user_decorator
from df_order.models import *
from django.core.paginator import Paginator,Page

# Create your views here.
def register(request):
    return render(request,'df_user/register.html')

def register_handle(request):
    #接受用户输入
    post = request.POST
    uname = post.get('user_name')
    upwd = post.get('pwd')
    upwd2 = post.get('cpwd')
    uemail = post.get('email')
    #判断两次输入的密码
    if upwd != upwd2:
        return redirect('/user/register/')
    #密码加密
    s1 = sha1()
    s1.update(upwd.encode("utf8"))
    upwd3 = s1.hexdigest()
    #创建对象
    user = UserInfo()
    user.uname = uname
    user.upwd = upwd3
    user.uemail = uemail
    user.save()
    #注册成功，转到登录页
    return redirect('/user/login/')

def register_exist(request):
    uname = request.GRT.get('uname')
    count = UserInfo.objects.filter(uname=uname).count()
    return JsonResponse({'count':count})

def login(request):
    uname = request.COOKIES.get('uname','')
    context = {'title':'用户登录','error_name':0,'error_pwd':0,'uname':uname}
    return render(request,'df_user/login.html',context)

# def login_handle(request):
#     """处理登录请求"""
#     post = request.POST
#     uname = post.get('username')
#     upwd = post.get('pwd')
#     re_pwd = post.get('remember_pwd', 0)
#
#     # 数据表查询
#     users = UserInfo.objects.filter(uname=uname)  # []
#     if len(users) == 1:
#         s1 = sha1()
#         s1.update(upwd.encode("utf8"))
#         if s1.hexdigest() == users[0].upwd:
#             res = HttpResponseRedirect('/user/info/')
#
#             # 记住用户名密码
#             if re_pwd != 0:
#                 res.set_cookie('uname', uname)
#             else:
#                 res.set_cookie('uname', '', max_age=-1)
#             request.session['user_id'] = users[0].id  # 可以直接通过id号查信息
#             request.session['user_name'] = uname  # 很多页面用到姓名
#             return res
#         else:
#             context = {
#                 'title': '用户登录',
#                 'error_name': 0,
#                 'error_pwd': 1,
#                 'uname': uname,
#                 'upwd': upwd
#             }
#             return render(request, 'user/login.html', context)
#     else:
#         context = {
#             'title': '用户登录',
#             'error_name': 1,
#             'error_pwd': 0,
#             'uname': uname,
#             'upwd': upwd
#         }
#         return render(request, 'user/login.html', context)
def login_handle(request):
    post = request.POST
    uname = post.get('username')
    upwd = post.get('pwd')
    jizhu = post.get('jizhu',0)
    #根据用户名查询对象
    # user = UserInfo.objects.filter(uname=uname)
    # print(uname)
    #判断：如果未查到在用户名错，如果查到再判断密码是否正确，正确则转到用户中心
    user = UserInfo.objects.filter(uname=uname)  # []
    if len(user) == 1:
        s1 = sha1()
        print(1)
        s1.update(upwd.encode("utf8"))
        if s1.hexdigest() == user[0].upwd:
            red = HttpResponseRedirect('/user/info/')
            if jizhu!=0:
                red.set_cookie('uname',uname)
                print(3)
            else:
                red.set_cookie('uname','',max_age=-1)
            request.session['user_id'] = user[0].id
            request.session['user_name'] = uname
            print(2)
            print(request.session['user_name'])
            return red
        else:
            print('1')
            context = {'title': '用户登录', 'error_name': 0, 'error_pwd': 1, 'uname': uname,'upwd':upwd}
            return render(request,'df_user/login.html',context)
    else:
        print('2')
        context = {'title': '用户登录', 'error_name': 1, 'error_pwd': 0, 'uname': uname,'upwd':upwd}
        return render(request,'df_user/login.html',context)

@user_decorator.login
def info(request):

    user_email = UserInfo.objects.get(id = request.session['user_id']).uemail
    #最近浏览
    goods_ids = request.COOKIES.get('goods_ids','')
    goods_ids1 = goods_ids.split(',')
    goods_list = []
    if goods_ids != '':
        goods_ids = goods_ids.split(',')
        for goods_id in goods_ids:
            goods_list.append(GoodsInfo.objects.get(id=int(goods_id)))
    user = UserInfo.objects.get(id=request.session['user_id'])
    goods = GoodsInfo()
    context = {
        'title':'用户中心',
        'user':user,
        'goods_list':goods_list,
    }
    return render(request,'df_user/user_center_info.html',context)


@user_decorator.login
def order(request,pindex):
    order_list = OrderInfo.objects.filter(user_id=request.session['user_id']).order_by('oid')
    paginator = Paginator(order_list,2)
    if pindex=='':
        pindex='1'
    page = paginator.page(int(pindex))
    context = {'title': '天天生鲜用户中心',
               'paginator': paginator,
               'page': page, }
    return render(request,'df_user/user_center_order.html',context)

@user_decorator.login
def site(request):
    user = UserInfo.objects.get(id = request.session['user_id'])
    if request.method == 'POST':
        post = request.POST
        user.ushou = post.get('ushou')
        user.uaddress = post.get('uaddress')
        user.uyoubian = post.get('uyoubian')
        user.uphone = post.get('uphone')
        user.save()
    context={'tiele':'用户中心','user':user}
    return render(request,'df_user/user_center_site.html',context)


def logout(request):
	request.session.flush()
	return redirect('/user/login/')

# def logout(request):
#     request.sission.flush()
#     return redirect('/')

templates/df_user/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-登录</title>
	<link rel="stylesheet" type="text/css" href="../../static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="../../static/css/main.css">

</head>
<body>
	<script>
		$(function () {
			name_error = false;
			pwd_error = false;

			if ({{ error_name }}==1){
			    $('.user_error').html('用户名错误').show();
			}

			if ({{ error_pwd }}==1){
			    $('.pwd_error').html('密码错误').show();
			}

			$('.name_input').blur(function () {
				if ($('.name_input').val().length==0){
				    $('.user_error').html("请输入用户名").show();
				    user_error=false
				}else {
					name_error=true;
					$('.user_error').hide();
				}
            });

			$('.pass_input').blur(function () {
				if ($('.name_input').val().length==0){
				    $('.pwd_error').html("请输入密码").show();
				    user_error=false;
				}else {
					pwd_error=true;
					$('.pwd_error').hide();
				}
            })
        })
	</script>

	<div class="login_top clearfix">
		<a href="../df_goods/index.html" class="login_logo"><img src="../../static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="../register">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/user/login_handle/" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="jizhu" value="1" checked="'checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

</body>
</html>

templates/df_user/register.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-注册</title>
	<link rel="stylesheet" type="text/css" href="../../static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="../../static/css/main.css">
	<script type="text/javascript" src="../../static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="../../static/js/register.js"></script>
</head>
<body>
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="../../static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="/user/register_handle/" method="post">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

templates/df_user/user_center_info.html
{% extends 'base.html' %}
{% block body %}

	<div class="search_bar clearfix">
		<a href="/goods/index" class="logo fl"><img src="../../static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/" class="active">· 个人信息</a></li>
				<li><a href="/user/order/1/">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.uname }}</li>
							<li><span>联系方式：</span>{{ user.uphone }}</li>
							<li><span>联系地址：</span>{{ user.uaddress }}</li>
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                        {% for g in goods_list %}
				<li>
{#				<li>#}
					<a href="/{{goods.id}}/"><img src="/static/{{goods.gpic}}"></a>
					<h4><a href="/{{goods.id}}/">{{goods.gtitle}}</a></h4>
					<div class="operate">
						<span class="prize">￥{{goods.gprice}}</span>
						<span class="unit">{{goods.gprice}}/{{goods.gunit}}</span>
						<a href="/cart/" class="add_goods" title="加入购物车"></a>
					</div>
{#				</li>#}
				</li>
                        {% endfor %}

{##}
{#				<li>#}
{#					<a href="#"><img src="../../static/images/goods/goods004.jpg"></a>#}
{#					<h4><a href="#">吐鲁番梨光杏</a></h4>#}
{#					<div class="operate">#}
{#						<span class="prize">￥5.50</span>#}
{#						<span class="unit">5.50/500g</span>#}
{#						<a href="#" class="add_goods" title="加入购物车"></a>#}
{#					</div>#}
{#				</li>#}
{##}
{#				<li>#}
{#					<a href="#"><img src="../../static/images/goods/goods005.jpg"></a>#}
{#					<h4><a href="#">黄肉桃</a></h4>#}
{#					<div class="operate">#}
{#						<span class="prize">￥10.00</span>#}
{#						<span class="unit">10.00/500g</span>#}
{#						<a href="#" class="add_goods" title="加入购物车"></a>#}
{#					</div>#}
{#				</li>#}
{##}
{#				<li>#}
{#					<a href="#"><img src="../../static/images/goods/goods006.jpg"></a>#}
{#					<h4><a href="#">进口西梅</a></h4>#}
{#					<div class="operate">#}
{#						<span class="prize">￥28.80</span>#}
{#						<span class="unit">28.8/500g</span>#}
{#						<a href="#" class="add_goods" title="加入购物车"></a>#}
{#					</div>#}
{#				</li>#}
{##}
{#				<li>#}
{#					<a href="#"><img src="../../static/images/goods/goods007.jpg"></a>#}
{#					<h4><a href="#">香梨</a></h4>#}
{#					<div class="operate">#}
{#						<span class="prize">￥6.45</span>#}
{#						<span class="unit">6.45/500g</span>#}
{#						<a href="#" class="add_goods" title="加入购物车"></a>#}
{#					</div>#}
{#				</li>#}
			</ul>
		</div>
		</div>
	</div>

{% endblock body %}

templates/df_user/user_center_order.html
{% extends 'base.html' %}

        {% block head %}

        {% endblock head %}


        {% block body %}


	<div class="search_bar clearfix">
		<a href="/goods/index" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/1/" class="active">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
    {%if paginator.count > 0%}
		  {%for order in page%}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{order.odate}}</li>
					<li class="col02">订单号：{{order.oid}}</li>
					<li class="col02 stress">{%if order.oIsPay%}已支付{%else%}未支付{%endif%}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
							   {%for detail in order.orderdetailinfo_set.all%}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="/static/{{detail.goods.gpic}}"></li>
									<li class="col02">{{detail.goods.gtitle|slice:'10'}}<em><span>{{detail.price}}</span>元/{{detail.goods.gunit}}</em></li>
									<li class="col03">{{detail.count}}</li>
									<li class="col04">0元</li>
								</ul>
								{%endfor%}
								</td>
							<td width="15%">{{order.ototal}}元</td>
							{%if order.oIsPay%}
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
							{%else%}
						<td width="15%">待付款</td>
						<td width="15%"><a href="/order/pay{{order.oid}}/" class="oper_btn">去付款</a></td>
						{%endif%}
						</tr>
					</tbody>
				</table>
      {%endfor%}

				<div class="pagenation">
				{%if page.has_previous%}
					<a href="/user/order/{{page.previous_page_number}}"><上一页</a>
					{%endif%}

					{%for pindex in paginator.page_range%}
					{%if pindex == page.number%}
					<a href="#" class=active>{{pindex}}</a>
					{%else%}
					<a href="/user/order/{{pindex}}/">{{pindex}}</a>
					{%endif%}
					{%endfor%}

					{%if page.has_next%}
				<a href="/user/order/{{page.next_page_number}}/">下一页></a>
				{%endif%}
				</div>
				{%else%}
			暂无订单信息
			{%endif%}
		</div>
	</div>


            {#				<ul class="order_list_th w978 clearfix">#}
{#					<li class="col01">2016-8-21 17:36:24</li>#}
{#					<li class="col02">订单号：56872934</li>#}
{#					<li class="col02 stress">未支付</li>		#}
{#				</ul>#}
{##}
{#				<table class="order_list_table w980">#}
{#					<tbody>#}
{#						<tr>#}
{#							<td width="55%">#}
{##}
{##}
{#							</td>#}
{#							<td width="15%">33.60元</td>#}
{#							<td width="15%">待付款</td>#}
{#							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>#}
{#						</tr>#}
{#					</tbody>#}
{#				</table>#}
{#				#}
{#				<ul class="order_list_th w978 clearfix">#}
{#					<li class="col01">2016-8-21 17:36:24</li>#}
{#					<li class="col02">订单号：56872934</li>#}
{#					<li class="col02 stress">已支付</li>			#}
{#				</ul>#}
{#				<table class="order_list_table w980">#}
{#					<tbody>#}
{#						<tr>#}
{#							<td width="55%">#}
{#								<ul class="order_goods_list clearfix">					#}
{#									<li class="col01"><img src="../../static/images/goods02.jpg"></li>#}
{#									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	#}
{#									<li class="col03">1</li>#}
{#									<li class="col04">11.80元</li>	#}
{#								</ul>#}
{#								<ul class="order_goods_list clearfix">					#}
{#									<li class="col01"><img src="../../static/images/goods02.jpg"></li>#}
{#									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	#}
{#									<li class="col03">1</li>#}
{#									<li class="col04">11.80元</li>	#}
{#								</ul>#}
{#							</td>#}
{#							<td width="15%">33.60元</td>#}
{#							<td width="15%">已付款</td>#}
{#							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>#}
{#						</tr>#}
{#					</tbody>#}
{#				</table>#}
{##}
{#				<div class="pagenation">#}
{#					<a href="#"><上一页</a>#}
{#					<a href="#" class="active">1</a>#}
{#					<a href="#">2</a>#}
{#					<a href="#">3</a>#}
{#					<a href="#">4</a>#}
{#					<a href="#">5</a>#}
{#					<a href="#">下一页></a>#}
{#				</div>#}
{#		</div>#}
{#	</div>#}


       {% endblock body %}

templates/df_user/user_center_site.html
{% extends 'base.html' %}

{% block body %}
	<div class="search_bar clearfix">
		<a href="/goods/index" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/1/">· 全部订单</a></li>
				<li><a href="/user/site/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ user.uaddress }}({{ user.uname }}收){{ user.uphone }}</dd>
					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/site/" method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ushou">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area"name="uaddress"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="uyoubian">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="uphone">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{% endblock body %}